version: "v2.29.7-desktop.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    networks:
      - practice-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DOCKER_HOST}:5432/${POSTGRES_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - minio
    env_file:
      - .properties
    networks:
      - practice-net
  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - app-network
    environment:
      - MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    env_file:
      - .properties
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

volumes:
  pgdbdata: null
  minio-data:
    driver: local

networks:
  practice-net:
