#version: "v2.29.7-desktop.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: fit_hub
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - practice-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/fit_hub"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - minio
    env_file:
      - .env
    networks:
      - practice-net
  frontend:
    build:
      context: ./FitHubFrontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "3000:3000"
    networks:
      - practice-net
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/ect/nginx/nginx.conf'
    depends_on:
      - app
      - frontend
    networks:
      - practice-net

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
    networks:
      - practice-net

volumes:
  pgdbdata:
    driver: local
  minio-data:
    driver: local

networks:
  practice-net: