spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: FitHub
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fit_hub
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        showSql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

jwt_secret: ${JWT_SECRET}

server:
  port: 8081
  error:
    includeMessage: always

minio:
  url: ${MINIO_URL}
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}