spring:
  config:
    import: classpath:static/.properties
  application:
    name: FitHub
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fit_hub
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        showSql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

jwt_secret: MIIEogI0Lj9FkWcfmLcpGlSXTO+Ww1L7EG8mRex97UVokJQRRA452V2vCO6S5ETgpnfad36de3MUxHgCOX3qL382Qx9THVmbmaq+PT3NtRae1FZPwjddQ14V905kyQFLamAA5YAAKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVhkGNnSxXQrTkvDOIUddSKOzHHgSg4nY6K02ecyT0PPmUZvtRpWrnBjcEVtHEJNpha4s38XMpayr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyrMrmYtjCZVWgaOYIhwrXwKLqPr11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J95d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQABAoIBACiARq2wkltjtcjs+lf4s4OxpzGXSW4HvtHEJNp

server:
  port: 8081
  error:
    includeMessage: always

minio:
  url: ${MINIO_URL}
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
#minio:
#  url: http://localhost:9000
#  access_key: minioadmin
#  secret_key: minioadmin
#  bucket: images
